server:
  port: 8381
spring:
  profiles:
    active: test
  application:
    name: cloud_redis
  redis:
    #单机配置
    #host: 192.168.150.129
    #port: 6381
    password: 123456
    database: 0
    timeout: 10s
    ssl: false
    #集群配置
    cluster:
      max-redirects: 3
      nodes:
        - 192.168.150.129:6381
        - 192.168.150.129:6382
        - 192.168.150.129:6383
        - 192.168.150.129:6384
        - 192.168.150.129:6385
        - 192.168.150.129:6386
    #哨兵配置
    #sentinel:
     # master:
     # nodes:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1s
        min-idle: 1

