#集群模式
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: 123456
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer:
    class: org.redisson.connection.balancer.RoundRobinLoadBalancer
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  nodeAddresses:
    - "redis://192.168.150.129:6381"
    - "redis://192.168.150.129:6382"
    - "redis://192.168.150.129:6383"
    - "redis://192.168.150.129:6384"
    - "redis://192.168.150.129:6385"
    - "redis://192.168.150.129:6386"
  scanInterval: 1000
threads: 0
nettyThreads: 0
codec:
  class: org.redisson.codec.JsonJacksonCodec
transportMode: NIO