server:
  port: 8053

spring:
  application:
    name: cli_security_8053
  datasource:
    url: jdbc:mysql://192.168.209.100:3306/security_rbac?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # Hikari 连接池配置
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1


# mybatis-plus配置
mybatis-plus:
  check-config-location: true
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: me.bruceli.security.entity
  configuration:
    #开启驼峰
    map-underscore-to-camel-case: true
    #是否缓存
    cache-enabled: false
    #日志实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #全局配置
  global-config:
    #数据库配置
    db-config:
      #主键生成策略
      id-type: ASSIGN_ID
      #数据库大写下划线转换
      capital-mode: false
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0


